export const GET ="GET";
export const ADD ="ADD";
export const PUT ="PUT";
export const DELETE ="DELETE";
export const ERROR ="ERROR";
export const POST_LOGIN = "POST";
export const POST_REGISTER = "POST"
export const ADD_POST = "ADD_POST";
export const POST = "POST";
export const GET_MOVIE = "GET_MOVIE"
export const CHANGE_AVATAR = "CHANGE_AVATAR"
export const GET_MOVIE_ACTION = "GET_MOVIE_ACTION"
export const GET_MOVIE_DRAMA = "GET_MOVIE_DRAMA"
export const GET_MOVIE_ADVENTURE ="GET_MOVIE_ADVENTURE"